escapeApp.factory('LockFactory', [
	function LockFactory() {
		'use strict';

		return [{
			track: 1,
			lockIcon: 'anchor',
			code: '32-0-20',
			opens: 'monopoly',
			visible: true
		}, {
			track: 1,
			lockIcon: 'bomb',
			code: '2-20-38',
			opens: 'yahtzee',
			visible: true
		}, {
			track: 1,
			lockIcon: 'university',
			code: '1-9-35',
			opens: 'scrabble',
			visible: true
		}, {
			track: 1,
			lockIcon: 'birthday-cake',
			code: '14-29-11',
			opens: 'jigsaw',
			visible: true
		}, {
			track: 2,
			lockIcon: 'gavel',
			code: '30-5-33',
			opens: 'clue',
			visible: true
		}, {
			track: 2,
			lockIcon: 'globe',
			code: '9-21-37',
			opens: 'guessWho',
			visible: true
		}, {
			track: 2,
			lockIcon: 'scissors',
			code: '11-21-37',
			opens: 'chess',
			visible: true
		}, {
			track: 2,
			lockIcon: 'diamond',
			code: '30-38-24',
			opens: 'crossword',
			visible: true
		}, {
			track: 2,
			lockIcon: 'rocket',
			code: '18-25-7',
			opens: 'jigsaw',
			visible: true
		}, {
			track: 3,
			lockIcon: 'tachometer',
			code: '24-4-27',
			opens: 'connect4',
			visible: true
		}, {
			track: 3,
			lockIcon: 'tree',
			code: '23-7-26',
			opens: 'fiveRoutes',
			visible: true
		}, {
			track: 3,
			lockIcon: 'motorcycle',
			code: '28-36-16',
			opens: 'wordFind',
			visible: true
		}, {
			track: 3,
			lockIcon: 'paw',
			code: '36-11-37',
			opens: 'taboo',
			visible: true
		}, {
			track: 3,
			lockIcon: 'ticket',
			code: '0-0-0',
			opens: 'jigsaw',
			visible: true
		}];
	}
]);
