escapeApp.factory('LockFactory', [
	function LockFactory() {
		'use strict';

		return [{
			track: 'a',
			lockIcon: 'anchor',
			code: '32-0-20',
			opens: 'monopoly'
		}, {
			track: 'a',
			lockIcon: 'bomb',
			code: '2-20-38',
			opens: 'yahtzee'
		}, {
			track: 'a',
			lockIcon: 'university',
			code: '1-9-35',
			opens: 'scrabble'
		}, {
			track: 'a',
			lockIcon: 'birthday-cake',
			code: '14-29-11',
			opens: 'jigsaw'
		}, {
			track: 'b',
			lockIcon: 'gavel',
			code: '30-5-33',
			opens: 'clue'
		}, {
			track: 'b',
			lockIcon: 'globe',
			code: '9-21-37',
			opens: 'guessWho'
		}, {
			track: 'b',
			lockIcon: 'scissors',
			code: '11-21-37',
			opens: 'chess'
		}, {
			track: 'b',
			lockIcon: 'diamond',
			code: '30-38-24',
			opens: 'crossword'
		}, {
			track: 'b',
			lockIcon: 'rocket',
			code: '18-25-7',
			opens: 'jigsaw'
		}, {
			track: 'c',
			lockIcon: 'tachometer',
			code: '24-4-27',
			opens: 'connect4'
		}, {
			track: 'c',
			lockIcon: 'tree',
			code: '23-7-26',
			opens: 'fiveRoutes'
		}, {
			track: 'c',
			lockIcon: 'motorcycle',
			code: '28-36-16',
			opens: 'wordFind'
		}, {
			track: 'c',
			lockIcon: 'paw',
			code: '36-11-37',
			opens: 'taboo'
		}, {
			track: 'c',
			lockIcon: 'ticket',
			code: '0-0-0',
			opens: 'jigsaw'
		}];
	}
]);
